### ISSUE TITLE
Append to character values vector to dictionary

### ISSUE THREAD

**Issue by kevalshah90** [mkuhn/dict#6]
Hi, First of all. Thanks so much for this dict implementation in R. This has been extremely helpful. I was wondering if there is a way to append to values vector? 

I have a dictionary within a for loop and I was hoping to add to the dictionary based on current values initialized in the loop. 

```
list1 = "foo","bar","hop" 
list2 = "ucla","oop","iop"
```

```
for(j in 1:length(Dates)) {
     dict[[ d[j] ]] <- list[j], list1[j]
} 
```
 
I would like to do something along the lines of, 

```
for(j in 1:length(Dates)) {
     dict[[ d[j] ]] <- append( list[j], list1[j])
} 
```

Thanks, again!

**Comment by mkuhn** [comment]
I'm not sure I understand your aim. Is it similar to the `numvecdict` described at the bottom of the [README](https://github.com/mkuhn/dict/blob/master/README.md)? If yes, then you could try to take the implementation of it and replace the number vectors by character vectors.

**Comment by kevalshah90** [comment]
I was able to figure out a work around. My sincere thanks to you for writing this. This library has been of incredible help!
